spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: arun
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: arun
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
      
      
      
